### ISSUE TITLE
Release 1.0.0 (with breaking changes)

### ISSUE THREAD

**Issue by oliverklee** [mjaschen/collmex#113]
This would allow Semantic Versioning to finally make sense for this package.

These are the things I'd like to get in for 1.0.0:

- [x] #111 require PHP >= 7.1
- [x] #112 upgrade PHPUnit
- [x] #133 use strict types
- [x] #134 add return types and nullable types
- [x] #124 Fix the return type of ZipResponse::getCsvResponse

**Comment by mjaschen** [comment]
The perfect moment for that would be after dropping PHP 7.0 ;-)

**Comment by oliverklee** [comment]
These are the things I'd like to get in for 1.0.0:

- require PHP >= 7.1
- use strict types
- change one API where types are ambiguous (I'll create a separate ticket to discuss my plan)

**Comment by Argee88** [comment]
As long as not all collmex-endpoints are implemented, I don't feel like there should be a major release

**Comment by oliverklee** [comment]
@Argee88 Are you familiar with semantic versioning? If not, you might want to take a look at https://semver.org/ .

**Comment by mjaschen** [comment]
@Argee88 We cannot ensure that all endpoints are implemented at any given time because Collmex permanently adds new ones. Adding new endpoints wouldn't break the API in a backwards incompatible way, therefore I don't see a problem in releasing a 1.0.0.

**Comment by Argee88** [comment]
Okay, I won't put up a fight ;)
However, I was talking about the existing ones and not about future changes to the API. Of course, you have to find a point, where you make a major release...

**Comment by oliverklee** [comment]
@mjaschen Would you be willing to add the changes from 0.11.1 and 0.12.0 to the changelog in the meantime?

**Comment by mjaschen** [comment]
I'm on it.

**Comment by oliverklee** [comment]
I also propose we add the corresponding lines from the changelog to the releases here in GitHub. Then the releases will look like this or this: https://github.com/MyIntervals/emogrifier/releases https://github.com/oliverklee/ext-seminars/releases

**Comment by Argee88** [comment]
Hi!
When will the release of 1.0 be? Since #179 is resolved I'd like to use it right away beacause this is a security update...

**Comment by oliverklee** [comment]
@Argee88 Just for the record: #178 isn't a security update.

**Comment by Argee88** [comment]
Never talked about #178 though...

**Comment by oliverklee** [comment]
Oh, sorry, my bad. It was a typo. I actually indeed meant that #179 isn't a security fix (in the sense that it fixes a vulnerability).

**Comment by Argee88** [comment]
Yeah, no. Anywho, I'd like to get an estimated date, which was the initial question

**Comment by oliverklee** [comment]
@mjaschen I think the project now is ready for version 1.0.0. If everything is okay from your side as well, could you please release during the next few days? Thanks!

**Comment by oliverklee** [comment]
1.0.0 is out of the door. 🎆
